### ISSUE TITLE
miami dade dupe events

### ISSUE THREAD

**Issue by fgregg** [opencivicdata/scrapers-us-municipal#113]
hi @rshorey 

there's a bunch of events aug 8 that are all the exact same except for location http://www.miamidade.gov/cob/county-commission-calendar.asp?next=nex

do you know whats up?

**Comment by ErnieAtLYD** [comment]
@fgregg: I can give some context: Since the county is geographically large (all of Southeastern Florida) 	the Mayor's FY 2016-17 Proposed Budget Public Meetings are broadcasted throughout the county. Not sure how that should/is reflected inside Councilmatic.

**Comment by fgregg** [comment]
Hmm... well, currently the OCD models only allow events to have a single location. Thoughts on this @jpmckinney ?

**Comment by fgregg** [comment]
I think the short term fix is to handle this event especially, and give it a no location.

**Comment by jpmckinney** [comment]
What is/are the real location(s) of the event?

**Comment by ErnieAtLYD** [comment]
@jpmckinney: The budget hearings are usually filmed in the Stephen P Clark Government Center, which is sort of the default value of sorts anyway.

**Comment by jpmckinney** [comment]
I'm trying to confirm why/whether the event is actually in multiple locations, per @fgregg's comment. It doesn't sound there are multiple locations.

**Comment by fgregg** [comment]
I think it's like a closed circuit feed. right? In order to watch it you
have to go to one of these locations?

**Comment by jpmckinney** [comment]
In my view, the reality is that the event itself has only one location; if you want to attend the event, you have to be at that location. A 'viewing party' might have its own location, and its own affordances.

**Comment by fgregg** [comment]
So, what do you want to do @ErnieAtLYD ?

**Comment by ErnieAtLYD** [comment]
It is technically a close circuit showing, yeah. I have no issues either way - sounds like what's easier to implement is one event at Government Center and not having subevents.

**Comment by fgregg** [comment]
None of the events show "Government center" as the location. http://www.miamidade.gov/cob/county-commission-calendar.asp?next=cur
