### ISSUE TITLE
Duplicated sponsorships

### ISSUE THREAD

**Issue by evz** [opencivicdata/scrapers-us-municipal#119]
It looks like, at least in Chicago, we have quite a few duplicated sponsorships. 

Here's one that has three Rahms (one as primary and two as regular): 
http://ocd.datamade.us/ocd-bill/0dd60741-c2cb-4f44-b116-81b2635f43af/

Here's a few more that just have duplicated sponsors:
http://ocd.datamade.us/ocd-bill/1e2d8a83-455c-4d69-bdb8-b34b4fcbad38/
http://ocd.datamade.us/ocd-bill/5b0cd2af-a5bc-49ee-9d96-d8ef979e8f2c/
http://ocd.datamade.us/ocd-bill/667c1caa-9003-4ba1-bb9a-b811b599b7c0/

**Comment by fgregg** [comment]
Fixed
