### ISSUE TITLE
Some OCD bill IDs have the same identifiers

### ISSUE THREAD

**Issue by evz** [opencivicdata/scrapers-us-municipal#120]
In Chicago I found a few city council identifiers that have more than one OCD ID. 

Sometimes it seems like we are getting the wrong identifier:

http://ocd.datamade.us/ocd-bill/5e946fad-fb6e-4095-aa58-8d34622eb861/ (should be CL2014-3703)
http://ocd.datamade.us/ocd-bill/281bb105-9b8c-43f0-a707-e8dc77eaab6c/

Sometimes it seems like we are making more than one OCD ID for a single identifier:

http://ocd.datamade.us/ocd-bill/43388e6d-5904-4988-8209-ccd20cd368b4/
http://ocd.datamade.us/ocd-bill/d95638f4-cc93-46d3-a155-192ac1a37b6e/

Here are some more examples:

Identifier CL 2016-239 
http://ocd.datamade.us/ocd-bill/0bcc2989-9c58-4351-81bf-314c9ac0cb94
http://ocd.datamade.us/ocd-bill/ocd-bill/9cfb8ce4-9cec-4a23-9949-0a4748a62706

Identifier CL 2016-240
http://ocd.datamade.us/ocd-bill/20edf5b0-6dbd-4c15-b05c-2d41373aae1d
http://ocd.datamade.us/ocd-bill/7e11c7d0-b22e-43a4-8987-353a63bbb4ed

Identifier CL 2016-241 
http://ocd.datamade.us/ocd-bill/0f3191b7-9fcb-47c0-8b65-a59a631ac870
http://ocd.datamade.us/ocd-bill/43261b98-343f-43d9-841e-669ec74b4ccf

Identifier CL 2016-242
http://ocd.datamade.us/ocd-bill/0a9d6f7a-08aa-4b30-b9de-2209e73267fb
http://ocd.datamade.us/ocd-bill/68d8e7ac-7491-4c3a-afad-d7701cc49104

Identifier CL 2016-243 
http://ocd.datamade.us/ocd-bill/9ab9d044-7818-4265-b35a-6e65b0116131
http://ocd.datamade.us/ocd-bill/e889b364-e1df-4913-a225-6ad61bc3a513

**Comment by fgregg** [comment]
Fixed this
