### ISSUE TITLE
Ad-hoc committee puzzlement.

### ISSUE THREAD

**Issue by reginafcompton** [opencivicdata/scrapers-us-municipal#122]
It seems that the members of Ad-Hoc committees do not have end dates.....why is this? are we missing something?

Also, do these committees have a "cycle," which might affect memberships (i.e., could members be duplicated)?

@fgregg

**Comment by fgregg** [comment]
Did we resolve this? I think we did.

**Comment by reginafcompton** [comment]
Yes. (We even have some explanatory text about it on the website: https://lametro.datamade.us/committees/)
