### ISSUE TITLE
Can you provide detailed tickets for web scrapers that folks could write for you?

### ISSUE THREAD

**Issue by jackiekazil** [opencivicdata/scrapers-us-municipal#24]
Can you provide detailed tickets for web scrapers that folks could write for you? 
I would like to have them for challenges as part of a tutorial that I am teaching: https://us.pycon.org/2015/schedule/presentation/318/

(Also, please let me know if you have other repos that might have these need also.)

**Comment by paultag** [comment]
Heyya, @jackiekazil !

I'll be at PyCon too, along with a few other Sunlighters -- we'll even be hosting our annual Open Gov sprint!

We were thinking of directing some energy at a few other scrapers, let me pull in @boblannon here

**Comment by jackiekazil** [comment]
:waves: @boblannon

**Comment by boblannon** [comment]
hey!  either I read your mind or you read mine.  I've been hacking on http://influence-usa.github.io for the past couple of days.  i have quite a few crawling and scraping tasks. Each icon in the table is a discrete task, with its own GH issue.  Soon I'll update those issues with instructions about how to get started each one.

**Comment by jackiekazil** [comment]
Sounds good! Thank you! /cc @sisiwei
