### ISSUE TITLE
Public hearings at same time as committee meeting

### ISSUE THREAD

**Issue by fgregg** [opencivicdata/scrapers-us-municipal#30]
So the finance committee has their normal meeting: https://chicago.legistar.com/MeetingDetail.aspx?ID=191000&GUID=F46D8B14-13E1-4500-A47D-428604931403&Options=info%7C

During which they will have two public hearings: 
https://chicago.legistar.com/MeetingDetail.aspx?ID=184426&GUID=0FB72168-5E0C-4F42-B782-E79DCCC1B9B6&Options=info%7C
https://chicago.legistar.com/MeetingDetail.aspx?ID=190991&GUID=14BD8DD5-4C57-4A11-AA09-D124C9551DB0&Options=info%7C

I'm not sure the right way to model this. 

Right, we can't just insert all these events because pupa thinks they are duplicates

Thoughts @jpmckinney, @paultag

**Comment by jpmckinney** [comment]
[Pupa's](http://docs.opencivicdata.org/en/latest/proposals/0004.html) Event model precedes [Popolo's](http://www.popoloproject.com/specs/event.html). Popolo's has a term for parent event, whereas Pupa doesn't. In Popolo, you can relate the public meetings as subevents of the "normal" meeting (unless I misunderstand the administrative distinctions here).

**Comment by fgregg** [comment]
That sound right.

**Comment by jpmckinney** [comment]
In that case, Pupa should at minimum implement a `parent_id` property (and at maximum align completely with Popolo, which I think just means `start_time` -> `start_date` and `end_time` -> `end_date`).

**Comment by fgregg** [comment]
@jpmckinnery seems like we need to start a OCD proposal!

**Comment by paultag** [comment]
We didn't use _date since we always have full datetimes

On Thu, May 21, 2015 at 5:02 PM, Forest Gregg <notifications@github.com>
wrote:

> @jpmckinnery seems like we need to start a OCD proposal!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencivicdata/scrapers-us-municipal/issues/30#issuecomment-104419171>
> .
>



-- 
Paul Tagliamonte
Software Developer | Sunlight Foundation

**Comment by jpmckinney** [comment]
Yes, but it's hard to build up a suite of tools that can all talk Popolo if some make small changes in vocabulary.
