### ISSUE TITLE
Chicago: missing bill R2023-0004485

### ISSUE THREAD

**Issue by derekeder** [opencivicdata/scrapers-us-municipal#380]
missing bill in Chicago: https://chicityclerkelms.chicago.gov/Matter/?matterId=DDF898D6-CD57-EE11-BE6E-001DD8098532

**Comment by fgregg** [comment]
okay, here's how this happened.

this item has a recordCreationDate of September 20, 2023. but the scraper doesn't check that field currently, it just checks the introduction and action fields, which were on September 14. 

so it didn't exist in the database until 6 days after the item was introduced, at which point it would not have been captured by our standard three day window on introductiondate.

so, i'll add recordCreationDate our checks
