### ISSUE TITLE
Chicago: missing vote_event on agenda item

### ISSUE THREAD

**Issue by derekeder** [opencivicdata/scrapers-us-municipal#381]
vote_event information is not being captured here: https://puddle.bunkum.us/chicago_council-c4abbd0/eventrelatedentity?_sort=id&agenda_item_id__exact=d1338b1e-e903-4b50-ad67-f7844b1eeeeb

**Comment by fgregg** [comment]
okay, figured this one out too. it's because the organization name used to link to identify the vote_event was using "city council" and not "chicago city council"
