### ISSUE TITLE
Chicago: duplicate events from different sources

### ISSUE THREAD

**Issue by derekeder** [opencivicdata/scrapers-us-municipal#382]
one is from Legistar another from the new eLMS

https://puddle.bunkum.us/chicago_council-c21cb25/event/ocd-event~2Fc977edb0-bd79-41dc-acb8-2b5b6dbf713c
https://puddle.bunkum.us/chicago_council-c21cb25/event/ocd-event~2Fe4b9ecc8-3bf4-4cc3-867a-0d9df6717dad

**Comment by fgregg** [comment]
we use [pupa_id to canonically identify events](https://github.com/opencivicdata/scrapers-us-municipal/blob/f577fa9920356da5ceff79495a7239708e8e45a0/chicago/events.py#L36). 

so events that we have pulled from both the new system and from legistar will duplicate. we should some database surgery and remove the legistar events and then do a full scrape of events from elms.

**Comment by fgregg** [comment]
i've fixed this.
