### ISSUE TITLE
Chicago: individual participants missing from event

### ISSUE THREAD

**Issue by derekeder** [opencivicdata/scrapers-us-municipal#383]
scraped data: https://puddle.bunkum.us/chicago_council-c21cb25/event/ocd-event~2Fc977edb0-bd79-41dc-acb8-2b5b6dbf713c

source: https://chicityclerkelms.chicago.gov/Meeting/?meetingId=3673BD4C-4F09-EE11-8F6D-001DD809B965

**Comment by fgregg** [comment]
rescraped this and this is now fixed
