### ISSUE TITLE
Chicago: missing action on bill

### ISSUE THREAD

**Issue by derekeder** [opencivicdata/scrapers-us-municipal#390]
Bill was substituted, but this is not captured: https://chicityclerkelms.chicago.gov/Matter/?matterId=F5A7CE69-4311-EE11-8F6C-001DD806D3F2

Puddle: https://puddle.bunkum.us/chicago_council-efc405c/bill/ocd-bill~2Fdd72064a-c1a9-4c0a-868c-7dbc3a85d46c

**Comment by fgregg** [comment]
This is missing because we have used to skip actions that do not say what body is responsible for the action, now we will default to the organization being the City Council. i'm also setting a flag in the extras on the bill action so we can make a report later to the clerks office.
