### ISSUE TITLE
Chicago: Capturing current controlling body of legislation

### ISSUE THREAD

**Issue by fgregg** [opencivicdata/scrapers-us-municipal#46]
We capture referral actions from the the city council to a committee, but I don't see anyway to record which committee the legislation was referred to. (we know it from Legistar)

We'll eventually know once the committee takes action on a piece of legsilation, but right now there doesn't seem to be a way of finding pending legislation in a committee.

@rshorey @paultag is that right? Any suggestions? Does this require a an OCDEP?

**Comment by fgregg** [comment]
related_entities would seem like it might be what I want, but nothing I put in there shows up in the API.

**Comment by fgregg** [comment]
For now, I'm going to stuff this into `extras`? Seem reasonable?

**Comment by paultag** [comment]
Wait, no back up, if things are going in and not coming out, that's a bug.
Example?

On Mon, Jun 1, 2015 at 12:08 PM, Forest Gregg <notifications@github.com>
wrote:

> For now, I'm going to stuff this into extras? Seem reasonable?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencivicdata/scrapers-us-municipal/issues/46#issuecomment-107611831>
> .
>



-- 
Paul Tagliamonte
Software Developer | Sunlight Foundation

**Comment by fgregg** [comment]
Hmm... okay. I'll make a PR with the related_entities thing.

**Comment by fgregg** [comment]
Here's an example of a bill http://api.opencivicdata.org/ocd-bill/ef8f92fe-e0a4-4004-b7a4-92e7ba6d6643/ 

I would like to indicate on that referral action that it was referred to the Committee on Finance: https://chicago.legistar.com/LegislationDetail.aspx?ID=2321132&GUID=1ADEE489-D20F-4FF4-8C19-4301C111D2F5

**Comment by paultag** [comment]
I think it's just not in the default serialization, it's still in the db

On Mon, Jun 1, 2015 at 1:08 PM, Forest Gregg <notifications@github.com>
wrote:

> Here's an example of a bill
> http://api.opencivicdata.org/ocd-bill/ef8f92fe-e0a4-4004-b7a4-92e7ba6d6643/
>
> I would like to indicate on that referral action that it was referred to
> the Committee on Finance:
> https://chicago.legistar.com/LegislationDetail.aspx?ID=2321132&GUID=1ADEE489-D20F-4FF4-8C19-4301C111D2F5
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencivicdata/scrapers-us-municipal/issues/46#issuecomment-107641589>
> .
>



-- 
Paul Tagliamonte
Software Developer | Sunlight Foundation

**Comment by fgregg** [comment]
So.. bug or not? Do you want to see that PR?

**Comment by paultag** [comment]
Did you PR Imago?

https://github.com/opencivicdata/imago/blob/master/imago/serialize.py

Looks like it just needs to be added there?

On Mon, Jun 1, 2015 at 1:28 PM, Forest Gregg <notifications@github.com>
wrote:

> So.. bug or not? Do you want to see that PR?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencivicdata/scrapers-us-municipal/issues/46#issuecomment-107646409>
> .
>



-- 
Paul Tagliamonte
Software Developer | Sunlight Foundation

**Comment by fgregg** [comment]
okee doke.
