### ISSUE TITLE
Should I associate posts with ocd-divisions

### ISSUE THREAD

**Issue by fgregg** [opencivicdata/scrapers-us-municipal#51]
The OCD-API has divisions for each of the wards:

http://api.opencivicdata.org/ocd-division/country%3Aus/state%3Ail/place%3Achicago/

Should I associate these to posts when the scraper creates posts? If so, how do I do that?

**Comment by rshorey** [comment]
A post can only have one division, so you'd have to decide whether the ward or city is the level you want to do this at. I think city-level makes more sense so you can look at the legislature as a whole from the same division. If there is a level of government that happens on the ward level that you want to scrape, though, it should probably go in there.

For example, NYC has city-level government (city council, I'd associate it with the city) and borough-level government (I'd associate with borough).

If you think this is the wrong way to go about it, I'd def be up for discussion.

**Comment by mileswwatkins** [comment]
@fgregg, is this resolved? If so, please close.

**Comment by fgregg** [comment]
I've tried to understand how
