### ISSUE TITLE
Conflict error for NYC action on bil

### ISSUE THREAD

**Issue by fgregg** [opencivicdata/scrapers-us-municipal#66]
Moxie is reporting an DuplicateItemError for an action on this bill: http://api.opencivicdata.org/ocd-bill/79d131fc-dedf-4f43-ab8f-3c406f6ccc39/, 

http://legistar.council.nyc.gov/LegislationDetail.aspx?ID=1796877&GUID=9F4422ED-4F21-409A-97A6-623A950F71BF
```
import votes...
Traceback (most recent call last):
  File "/usr/local/bin/pupa", line 9, in <module>
    load_entry_point('pupa==0.4.1', 'console_scripts', 'pupa')()
  File "/pupa/src/pupa/pupa/cli/__main__.py", line 71, in main
    subcommands[args.subcommand].handle(args, other)
  File "/pupa/src/pupa/pupa/cli/commands/update.py", line 244, in handle
    report['import'] = self.do_import(juris, args)
  File "/pupa/src/pupa/pupa/cli/commands/update.py", line 181, in do_import
    report.update(vote_importer.import_directory(datadir))
  File "/pupa/src/pupa/pupa/importers/base.py", line 169, in import_directory
    return self.import_data(json_stream())
  File "/pupa/src/pupa/pupa/importers/base.py", line 206, in import_data
    obj_id, what = self.import_item(data)
  File "/pupa/src/pupa/pupa/importers/base.py", line 241, in import_item
    raise DuplicateItemError(data, obj)
pupa.exceptions.DuplicateItemError: attempt to import data that would conflict with data already in the import: {'result': 'pass', 'extras': {}, 'legislative_session_id': UUID('1ca51a67-4d27-4649-bf34-c5849dfd30d6'), 'bill_id': 'ocd-bill/79d131fc-dedf-4f43-ab8f-3c406f6ccc39', 'identifier': '', 'motion_classification': ['passage'], 'motion_text': 'Approved, by Council', 'organization_id': 'ocd-organization/389257d3-aefe-42df-b3a2-a0d56d0ea731', 'start_date': '2014-05-14'} (already imported as Approved, by Council on M 63-2014 in New York City 2014 Regular Session Session)
```

**Comment by fgregg** [comment]
Okay, this is what I think is going on. 

It takes multiple hours to scrape nyc bills and in that time there may be some bill activity added to the legistar system. This can change the sort order and cause the same bill to be iterated through.  This only sometimes happens, of course.

Not sure what the best way to handle this is. Thoughts @mileswwatkins @rshorey

**Comment by fgregg** [comment]
This may actually be a deeper question. Who's responsibility is it to make sure that every bill object in a scrape is unique. The scraper or pupa? cc @jamesturk @jpmckinney @paultag

**Comment by rshorey** [comment]
I think this needs to be done by the scraper. Pupa throws errors for non-unique stuff, but it has no way of knowing what to resolve to if two things are not unique.

For NYC, perhaps it'd make sense to pull the whole bill list first, store it, and then access the individual bills so there's less time for things to change. Would that make sense in this case?
