### ISSUE TITLE
Should bill actions be in chronological order or reverse chronological order

### ISSUE THREAD

**Issue by fgregg** [opencivicdata/scrapers-us-municipal#73]
Right now the actions of bills are being entered in reverse chronological order for NYC and Chicago. Probably makes more sense to do it chronological order. Thoughts @cathydeng?

**Comment by cathydeng** [comment]
I'm currently reversing the list of actions before loading it into councilmatic, so ya, chronological order would make more sense & save a processing step

**Comment by fgregg** [comment]
Okay, @cathydeng watch out for this. will probably take a few days to propagate
