### ISSUE TITLE
Add Ann Arbor, Michigan?

### ISSUE THREAD

**Issue by vielmetti** [opencivicdata/scrapers-us-municipal#80]
Let me know what's possible to get started...

**Comment by fgregg** [comment]
Hi @vielmetti , 

No documentation exists at this point and the code is still in flux. That said, if you want to jump in you should study https://github.com/opencivicdata/scrapers-us-municipal/tree/master/nyc

These scrapers use the https://github.com/opencivicdata/python-legistar-scraper base classes.

**Comment by fgregg** [comment]
In particular,

1. Start by setting up pupa
2. Make sure you can run an existing scraper, like NYC
3. Run `pupa init annarbor` in the scrapers-us-municipal directory
4. Adapt the __init__.py file from NYC to work for your muni
5. I would then start with people or events. They are quite a bit easier than bills

**Comment by vielmetti** [comment]
Closed because ?

**Comment by fgregg** [comment]
There's not been any response or updates on this for over a year. Feel free to open up a PR if you are working on this scraper.

**Comment by vielmetti** [comment]
Do you have documentation that you didn't have when I enquired in 2015? I'm happy to take a look again.

**Comment by fgregg** [comment]
No, the guidance I gave above is the best I can offer.
